### ISSUE TITLE
F-droid

### ISSUE THREAD

**Issue by droped** [phcoder/SGit#4]
Sgit is already on f-droid. You could perhaps get your app in there too. I believe the app meets all the requirements.

**Comment by Foggalong** [comment]
+1 for F-Droid

**Comment by ghost** [comment]
+1 for F-Droid

I've tried creating the necessary addition to fdroiddata, by my limited knowledge of both gradle and the things installed on the official build-server of F-Droid prevent me from a successful build even locally so I'm very hesitant to create the actual pull-request... In case anyone with more experience wants to see where I started: https://gitlab.com/robertkosten/fdroiddata/commit/779e36789326baf91d6d0a3da7cca14cb785fb62

**Comment by monabat79** [comment]
Don't forget to use the reaction button on comments like I did.
+1 for Fdroid

**Comment by Foggalong** [comment]
@Nikitaw99 React buttons didn't exist when I commented :P

**Comment by monabat79** [comment]
@Foggalong Well, okay then.
